spring:
  application:
    name: OAuth-ResourceServer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      #自动更新
      ddl-auto: update
    #显示SQL
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  jackson:
    #设置空如何序列化
    default-property-inclusion: NON_EMPTY
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true
    property-naming-strategy: LOWER_CAMEL_CASE
server:
  port: 10085
  servlet:
    context-path: /api